import { type AppConfig } from "@repo/lib";

export const APP_CONFIG: AppConfig = {
  name: "homm-olden-era",
  title: "Heroes of Might & Magic: Olden Era",
  domain: "oldenera",
  supportedLocales: [
    "en",
    "fr",
    "de",
    "es",
    "ru",
    "pl",
    "cs",
    "hu",
    "tr",
    "uk",
    "ja",
    "ko",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: null,
  internalLinks: [
    {
      href: "/db/units",
      title: "config.internalLinks.units.title",
      linkText: "config.internalLinks.units.linkText",
      iconName: "Axe",
      description: "config.internalLinks.units.description",
    },
    {
      href: "/db/heroes",
      title: "config.internalLinks.heroes.title",
      linkText: "config.internalLinks.heroes.linkText",
      iconName: "Trophy",
      description: "config.internalLinks.heroes.description",
    },
    {
      href: "/db/spells",
      title: "config.internalLinks.spells.title",
      linkText: "config.internalLinks.spells.linkText",
      iconName: "ScrollText",
      description: "config.internalLinks.spells.description",
    },
    {
      href: "/db/items",
      title: "config.internalLinks.items.title",
      linkText: "config.internalLinks.items.linkText",
      iconName: "Gift",
      description: "config.internalLinks.items.description",
    },
    {
      href: "/db/skills",
      title: "config.internalLinks.skills.title",
      linkText: "config.internalLinks.skills.linkText",
      iconName: "BookOpen",
      description: "config.internalLinks.skills.description",
    },
    {
      href: "/db/factions",
      title: "config.internalLinks.factions.title",
      linkText: "config.internalLinks.factions.linkText",
      iconName: "ShieldCheck",
      description: "config.internalLinks.factions.description",
    },
    {
      href: "/db/buildings",
      title: "config.internalLinks.buildings.title",
      linkText: "config.internalLinks.buildings.linkText",
      iconName: "House",
      description: "config.internalLinks.buildings.description",
    },
    {
      href: "/db/map-objects",
      title: "config.internalLinks.map-objects.title",
      linkText: "config.internalLinks.map-objects.linkText",
      iconName: "MapPin",
      description: "config.internalLinks.map-objects.description",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: [
    "HoMM",
    "Olden Era",
    "Heroes of Might and Magic",
    "Database",
    "Units",
    "Heroes",
    "Spells",
    "Artifacts",
    "Skills",
    "Factions",
  ],
};
