import { resolveAppConfig } from "@repo/lib";

export const drakantos = resolveAppConfig({
  name: "drakantos",
  title: "Drakantos",
  domain: "drakantos",
  supportedLocales: ["en"],
  appUrl: null,
  internalLinks: [
    {
      href: "/db/creatures",
      title: "config.internalLinks.creatures.title",
      linkText: "config.internalLinks.creatures.linkText",
      iconName: "Bug",
      description: "config.internalLinks.creatures.description",
    },
    {
      href: "/db/items",
      title: "config.internalLinks.items.title",
      linkText: "config.internalLinks.items.linkText",
      iconName: "Gift",
      description: "config.internalLinks.items.description",
    },
    {
      href: "/db/outfits",
      title: "config.internalLinks.outfits.title",
      linkText: "config.internalLinks.outfits.linkText",
      iconName: "Axe",
      description: "config.internalLinks.outfits.description",
    },
    {
      href: "/db/places",
      title: "config.internalLinks.places.title",
      linkText: "config.internalLinks.places.linkText",
      iconName: "MapPin",
      description: "config.internalLinks.places.description",
    },
    {
      href: "/db/zones",
      title: "config.internalLinks.zones.title",
      linkText: "config.internalLinks.zones.linkText",
      iconName: "Map",
      description: "config.internalLinks.zones.description",
    },
    {
      href: "/db/story",
      title: "config.internalLinks.story.title",
      linkText: "config.internalLinks.story.linkText",
      iconName: "BookOpen",
      description: "config.internalLinks.story.description",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: [
    "Drakantos",
    "Drakantos Playtest",
    "MMORPG",
    "Database",
    "Bestiary",
    "Items",
    "Sprites",
  ],
  db: {
    heroSubtitle: "Game Database",
    searchPlaceholder: "Search creatures, items, places…",
    homeSections: [
      { href: "/db/creatures", type: "creatures", icon: "🐍" },
      { href: "/db/items", type: "items", icon: "◆" },
      { href: "/db/outfits", type: "outfits", icon: "⚔", extraTypes: ["effects", "distances"] },
      { href: "/db/places", type: "places", icon: "🏛" },
      { href: "/db/zones", type: "zones", icon: "🗺" },
      { href: "/db/story", type: "story", icon: "📜", extraTypes: ["guide"] },
    ],
    typeLabels: {
      creatures: "Creature",
      items: "Item",
      outfits: "Outfit",
      effects: "Effect",
      distances: "Distance Shot",
      places: "Place",
      zones: "Zone",
      story: "Story",
      guide: "Guide",
    },
    typeColors: {
      creatures: "bg-red-900/40 text-red-400",
      items: "bg-purple-900/40 text-purple-400",
      outfits: "bg-amber-900/40 text-amber-400",
      effects: "bg-cyan-900/40 text-cyan-400",
      distances: "bg-indigo-900/40 text-indigo-400",
      places: "bg-emerald-900/40 text-emerald-400",
      zones: "bg-teal-900/40 text-teal-400",
      story: "bg-yellow-900/40 text-yellow-400",
      guide: "bg-yellow-900/40 text-yellow-400",
    },
    languageCount: 1,
  },
});
