import { resolveAppConfig, DATA_FORGE_CDN_URL } from "@repo/lib";

export const gothic1Remake = resolveAppConfig({
  name: "gothic-1-remake",
  supportedLocales: [
    "en",
    "de",
    "fr",
    "es",
    "it",
    "pt-BR",
    "ru",
    "pl",
    "ja",
    "zh-CN",
  ],
  appUrl: "https://www.th.gl/companion-app",
  internalLinks: [
    {
      title: "Khorinis Map",
      description:
        "Explore the Colony on Khorinis with our interactive Gothic 1 Remake map — chests, fishing spots, focus stones, mining, crafting stations and more.",
      href: "/maps/Khorinis",
      iconName: "Map",
      bgImage: `${DATA_FORGE_CDN_URL}/gothic-1-remake/map-tiles/Khorinis/preview.webp?v=1`,
      linkText: "Explore the Khorinis Map",
    },
    {
      href: "/db/weapon",
      title: "Weapons",
      linkText: "Browse Weapons",
      iconName: "Axe",
      description: "Every weapon in the Gothic 1 Remake.",
    },
    {
      href: "/db/armor",
      title: "Armor",
      linkText: "Browse Armor",
      iconName: "ShieldCheck",
      description: "All armor sets and outfits.",
    },
    {
      href: "/db/potion",
      title: "Potions",
      linkText: "Browse Potions",
      iconName: "Gift",
      description: "Potions, elixirs and brews.",
    },
    {
      href: "/db/herb",
      title: "Herbs",
      linkText: "Browse Herbs",
      iconName: "BookOpen",
      description: "Plants and herbs of the Colony.",
    },
    {
      href: "/db/trader",
      title: "Traders",
      linkText: "Browse Traders",
      iconName: "Handshake",
      description: "Every merchant and what they sell — weapons, runes, potions and more.",
    },
    {
      href: "/db/creature",
      title: "Bestiary",
      linkText: "Browse the Bestiary",
      iconName: "Bug",
      description: "Every creature of the Colony — attack damage and variants.",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: [
    "Gothic",
    "Gothic 1 Remake",
    "Khorinis",
    "The Colony",
    "Chests",
    "Focus Stones",
    "Ore",
    "Items",
  ],
  topFilters: ["chest", "fishing_spot", "focus_stone", "ore_vein"],
  db: {
    heroSubtitle: "Item Database",
    searchPlaceholder: "Search weapons, armor, potions, herbs...",
    // Every section below also becomes a header-nav item (de-duped against
    // internalLinks, overflowing into "More") — so materials/misc/runes/etc.
    // are reachable from the nav without hand-listing each in internalLinks.
    sectionsInNav: true,
    homeSections: [
      { href: "/db/weapon", type: "weapon", icon: "⚔" },
      { href: "/db/armor", type: "armor", icon: "🛡" },
      { href: "/db/potion", type: "potion", icon: "⚗" },
      { href: "/db/herb", type: "herb", icon: "🌿" },
      { href: "/db/food", type: "food", icon: "🍖" },
      { href: "/db/rune", type: "rune", icon: "🪨" },
      { href: "/db/scroll", type: "scroll", icon: "📜" },
      { href: "/db/amulet", type: "amulet", icon: "📿" },
      { href: "/db/ring", type: "ring", icon: "💍" },
      { href: "/db/material", type: "material", icon: "◆" },
      { href: "/db/key", type: "key", icon: "🗝" },
      { href: "/db/writing", type: "writing", icon: "📖" },
      { href: "/db/misc", type: "misc", icon: "🎒" },
      { href: "/db/trader", type: "trader", icon: "🪙" },
      { href: "/db/creature", type: "creature", icon: "🐾" },
    ],
    homeExtraLinks: [],
    typeLabels: {
      weapon: "Weapon",
      armor: "Armor",
      potion: "Potion",
      herb: "Herb",
      food: "Food",
      rune: "Rune",
      scroll: "Scroll",
      amulet: "Amulet",
      ring: "Ring",
      material: "Material",
      key: "Key",
      writing: "Book / Document",
      misc: "Miscellaneous",
      fishing: "Fishing",
      trader: "Trader",
      creature: "Bestiary",
    },
    typeColors: {
      weapon: "bg-red-900/40 text-red-400",
      armor: "bg-slate-700/40 text-slate-300",
      potion: "bg-emerald-900/40 text-emerald-400",
      herb: "bg-green-900/40 text-green-400",
      food: "bg-orange-900/40 text-orange-400",
      rune: "bg-purple-900/40 text-purple-400",
      scroll: "bg-amber-900/40 text-amber-400",
      amulet: "bg-cyan-900/40 text-cyan-400",
      ring: "bg-yellow-900/40 text-yellow-400",
      material: "bg-stone-700/40 text-stone-300",
      key: "bg-yellow-900/40 text-yellow-400",
      writing: "bg-sky-900/40 text-sky-400",
      misc: "bg-neutral-700/40 text-neutral-300",
      fishing: "bg-blue-900/40 text-blue-400",
      trader: "bg-amber-900/40 text-amber-400",
      creature: "bg-rose-900/40 text-rose-400",
    },
    languageCount: 10,
  },
});
