import { resolveAppConfig } from "@repo/lib";

export const hommOldenEra = resolveAppConfig({
  name: "homm-olden-era",
  supportedLocales: [
    "en",
    "fr",
    "de",
    "es",
    "ru",
    "pl",
    "cs",
    "hu",
    "tr",
    "uk",
    "ja",
    "ko",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: null,
  internalLinks: [
    {
      href: "/db/units",
      title: "config.internalLinks.units.title",
      linkText: "config.internalLinks.units.linkText",
      iconName: "Axe",
      description: "config.internalLinks.units.description",
    },
    {
      href: "/db/heroes",
      title: "config.internalLinks.heroes.title",
      linkText: "config.internalLinks.heroes.linkText",
      iconName: "Trophy",
      description: "config.internalLinks.heroes.description",
    },
    {
      href: "/db/spells",
      title: "config.internalLinks.spells.title",
      linkText: "config.internalLinks.spells.linkText",
      iconName: "ScrollText",
      description: "config.internalLinks.spells.description",
    },
    {
      href: "/db/artifacts",
      title: "config.internalLinks.items.title",
      linkText: "config.internalLinks.items.linkText",
      iconName: "Gift",
      description: "config.internalLinks.items.description",
    },
    {
      href: "/db/skills",
      title: "config.internalLinks.skills.title",
      linkText: "config.internalLinks.skills.linkText",
      iconName: "BookOpen",
      description: "config.internalLinks.skills.description",
    },
    {
      href: "/db/factions",
      title: "config.internalLinks.factions.title",
      linkText: "config.internalLinks.factions.linkText",
      iconName: "ShieldCheck",
      description: "config.internalLinks.factions.description",
    },
    {
      href: "/db/buildings",
      title: "config.internalLinks.buildings.title",
      linkText: "config.internalLinks.buildings.linkText",
      iconName: "House",
      description: "config.internalLinks.buildings.description",
    },
    {
      href: "/db/map-objects",
      title: "config.internalLinks.map-objects.title",
      linkText: "config.internalLinks.map-objects.linkText",
      iconName: "MapPin",
      description: "config.internalLinks.map-objects.description",
    },
    {
      href: "/db/maps",
      title: "config.internalLinks.maps.title",
      linkText: "config.internalLinks.maps.linkText",
      iconName: "Map",
      description: "config.internalLinks.maps.description",
    },
    {
      href: "/db/mechanics",
      title: "config.internalLinks.mechanics.title",
      linkText: "config.internalLinks.mechanics.linkText",
      iconName: "BookOpen",
      description: "config.internalLinks.mechanics.description",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: [
    "HoMM",
    "Olden Era",
    "Heroes of Might and Magic",
    "Database",
    "Units",
    "Heroes",
    "Spells",
    "Artifacts",
    "Skills",
    "Factions",
  ],
  db: {
    heroSubtitle: "Game Database",
    searchPlaceholder: "Search units, heroes, spells...",
    homeSections: [
      { href: "/db/units", type: "units", icon: "⚔" },
      { href: "/db/heroes", type: "heroes", icon: "👑" },
      { href: "/db/spells", type: "spells", icon: "✦" },
      { href: "/db/artifacts", type: "items", icon: "◆" },
      { href: "/db/skills", type: "skills", icon: "◎", extraTypes: ["sub_skills"] },
      {
        href: "/db/factions",
        type: "factions",
        icon: "⛊",
        extraTypes: ["specializations", "faction_laws"],
      },
      { href: "/db/buildings", type: "buildings", icon: "🏛" },
      { href: "/db/map-objects", type: "map_objects", icon: "🗺" },
      { href: "/db/maps", type: "maps", icon: "🧭" },
    ],
    homeExtraLinks: [
      {
        href: "/db/mechanics",
        title: "config.internalLinks.mechanics.title",
        description: "config.internalLinks.mechanics.description",
        icon: "📖",
      },
    ],
    typeLabels: {
      units: "Unit",
      heroes: "Hero",
      spells: "Spell",
      items: "Artifact",
      item_sets: "Item Set",
      skills: "Skill",
      sub_skills: "Sub-Skill",
      specializations: "Specialization",
      factions: "Faction",
      faction_laws: "Faction Law",
      buildings: "Building",
      map_objects: "Map Object",
      maps: "Map",
    },
    typeColors: {
      units: "bg-red-900/40 text-red-400",
      heroes: "bg-amber-900/40 text-amber-400",
      spells: "bg-indigo-900/40 text-indigo-400",
      items: "bg-purple-900/40 text-purple-400",
      item_sets: "bg-purple-900/40 text-purple-400",
      skills: "bg-emerald-900/40 text-emerald-400",
      sub_skills: "bg-emerald-900/40 text-emerald-400",
      specializations: "bg-cyan-900/40 text-cyan-400",
      factions: "bg-yellow-900/40 text-yellow-400",
      faction_laws: "bg-yellow-900/40 text-yellow-400",
      buildings: "bg-orange-900/40 text-orange-400",
      map_objects: "bg-teal-900/40 text-teal-400",
      maps: "bg-sky-900/40 text-sky-400",
    },
    languageCount: 14,
  },
});
