import { type AppConfig, getPreviewImageUrl } from "@repo/lib";

export const APP_CONFIG: AppConfig = {
  name: "once-human",
  title: "Once Human",
  domain: "oncehuman",
  supportedLocales: ["en"],
  appUrl: "https://www.th.gl/companion-app",
  internalLinks: [
    {
      href: "/maps/Deviation%20Secure",
      title: "Deviation Secure Map",
      description: "Navigate Deviation Secure with our interactive maps.",
      iconName: "Map",
      bgImage: getPreviewImageUrl("once-human", "default"),
      linkText: "Explore the Deviation Secure Map",
    },
    {
      href: "/maps/Manibus%20&%20Evolution's%20Call",
      title: "Manibus Evolution's Call Map",
      description:
        "Navigate Manibus Evolution's Call with our interactive maps.",
      iconName: "Map",
      bgImage: getPreviewImageUrl("once-human", "default"),
      linkText: "Explore the Manibus Evolution's Call Map",
    },
    {
      href: "/maps/Prismverse's%20Clash",
      title: "Prismverse's Clash Map",
      description: "Navigate Prismverse's Clash with our interactive maps.",
      iconName: "Map",
      bgImage: getPreviewImageUrl("once-human", "default"),
      linkText: "Explore the Prismverse's Clash  Map",
    },
    {
      href: "/maps/The%20Way%20of%20Winter",
      title: "The Way of Winter Map",
      description: "Navigate The Way of Winter with our interactive maps.",
      iconName: "Map",
      bgImage: getPreviewImageUrl("once-human", "default"),
      linkText: "Explore the The Way of Winter Map",
    },
    {
      href: "/maps/Endless%20Dream",
      title: "Endless Dream Map",
      description: "Navigate Endless Dream with our interactive maps.",
      iconName: "Map",
      bgImage: getPreviewImageUrl("once-human", "default"),
      linkText: "Explore the Endless Dream Map",
    },
    {
      href: "/mod-locations",
      title: "Mod Locations",
      iconName: "ArrowUp",
      linkText: "View Mod Locations",
    },
    {
      href: "/deviant-locations",
      title: "Deviant Locations",
      iconName: "Bug",
      linkText: "View Deviant Locations",
    },
    {
      href: "/remnants",
      title: "Remnants",
      iconName: "NotepadText",
      linkText: "View Remnants",
    },
    {
      href: "/regional-records",
      title: "Regional Records",
      iconName: "NotepadText",
      linkText: "View Regional Records",
    },
    {
      href: "/echoes-of-stardust",
      title: "Echoes Of Stardust",
      iconName: "NotepadText",
      linkText: "View Echoes Of Stardust",
    },
    {
      href: "/weapons",
      title: "Weapons",
      iconName: "Axe",
      linkText: "View Weapons",
    },
  ],
  markerOptions: {
    radius: 6,
    playerIcon: "player.webp",
    imageSprite: true,
    zPos: {
      xyMaxDistance: 200,
      zDistance: 3,
    },
    coordinateCopyFormat: "({x},{y})",
  },
  keywords: ["Ores", "Resources", "Riddles", "Deviants"],
  topFilters: ["mystical_crate", "landscape_viewpoint_camera", "hoard_loot_crate"],
};
