import { type AppConfig, getPreviewImageUrl } from "@repo/lib";

export const APP_CONFIG: AppConfig = {
  name: "palia",
  title: "Palia",
  domain: "palia",
  supportedLocales: [
    "en",
    "de",
    "es",
    "fr",
    "it",
    "ja",
    "ko",
    "pt-BR",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: "https://www.th.gl/companion-app",
  internalLinks: [
    {
      href: "/maps/Royal%20Highlands",
      title: "config.internalLinks.royalHighlands.title",
      description: "config.internalLinks.royalHighlands.description",
      linkText: "config.internalLinks.royalHighlands.linkText",
      iconName: "Map",
      bgImage: getPreviewImageUrl("palia", "AZ3_Root"),
    },
    {
      href: "/maps/Elderwood",
      title: "config.internalLinks.elderwood.title",
      description: "config.internalLinks.elderwood.description",
      linkText: "config.internalLinks.elderwood.linkText",
      iconName: "Map",
      bgImage: getPreviewImageUrl("palia", "AZ2_Root"),
    },
    {
      href: "/maps/Kilima%20Village",
      title: "config.internalLinks.kilima.title",
      description: "config.internalLinks.kilima.description",
      linkText: "config.internalLinks.kilima.linkText",
      iconName: "Map",
      bgImage: getPreviewImageUrl("palia", "VillageWorld"),
    },
    {
      href: "/maps/Bahari%20Bay",
      title: "config.internalLinks.bahari.title",
      description: "config.internalLinks.bahari.description",
      linkText: "config.internalLinks.bahari.linkText",
      iconName: "Map",
      bgImage: getPreviewImageUrl("palia", "AdventureZoneWorld"),
    },
    {
      href: "/maps/Fairgrounds",
      title: "config.internalLinks.fairgrounds.title",
      description: "config.internalLinks.fairgrounds.description",
      linkText: "config.internalLinks.fairgrounds.linkText",
      iconName: "Map",
      bgImage: getPreviewImageUrl("palia", "MajiMarket"),
    },
    {
      href: "/rummage-pile",
      title: "config.internalLinks.rummagePile.title",
      description: "config.internalLinks.rummagePile.description",
      linkText: "config.internalLinks.rummagePile.linkText",
      iconName: "MapPin",
      bgImage: "/rummage-pile.webp",
    },
    {
      href: "/leaderboard",
      title: "config.internalLinks.leaderboard.title",
      description: "config.internalLinks.leaderboard.description",
      linkText: "config.internalLinks.leaderboard.linkText",
      iconName: "Trophy",
      bgImage: "/leaderboard.webp",
    },
    {
      href: "/weekly-wants",
      title: "config.internalLinks.weeklyWants.title",
      description: "config.internalLinks.weeklyWants.description",
      linkText: "config.internalLinks.weeklyWants.linkText",
      iconName: "Gift",
      bgImage: "/weekly-wants.webp",
    },
  ],
  markerOptions: {
    radius: 6,
    playerIcon: "player.webp",
    imageSprite: true,
    zPos: {
      xyMaxDistance: 15000,
      zDistance: 400,
    },
    clusterPrecision: 5,
  },
  keywords: ["Rummage Pile", "Plushies", "Elderwood"],
};
