import { type AppConfig, getPreviewImageUrl } from "@repo/lib";

export const APP_CONFIG: AppConfig = {
  name: "conan-exiles",
  title: "Conan Exiles",
  domain: "conanexiles",
  supportedLocales: [
    "en",
    "de",
    "es",
    "fr",
    "it",
    "ja",
    "ko",
    "pl",
    "pt",
    "ru",
    "zh-Hans",
    "zh-Hant",
  ],
  appUrl: null,
  internalLinks: [
    {
      title: "Exiled Lands Map",
      description:
        "Navigate the Exiled Lands in Conan Exiles Enhanced (UE5). Find camps, dungeons, caves, vistas, wildlife, NPC factions, iron ore deposits, and more.",
      href: "/maps/Exiled%20Lands",
      iconName: "Map",
      bgImage: getPreviewImageUrl("conan-exiles", "ExiledLands", "2"),
      linkText: "Explore the Exiled Lands",
    },
    {
      title: "Isle of Siptah Map",
      description:
        "Explore the Isle of Siptah in Conan Exiles Enhanced. Find vaults, surge altars, camps, wildlife, and resource clusters.",
      href: "/maps/Isle%20of%20Siptah",
      iconName: "Map",
      bgImage: getPreviewImageUrl("conan-exiles", "IsleOfSiptah", "2"),
      linkText: "Explore the Isle of Siptah",
    },
  ],
  promoLinks: [],
  externalLinks: [
    {
      href: "https://conanexiles.gaming.tools/",
      title: "Database",
    },
  ],
  keywords: [
    "Conan Exiles Enhanced",
    "Exiled Lands",
    "Isle of Siptah",
    "Camps",
    "Dungeons",
    "Caves",
    "Vaults",
    "Surge Altars",
    "Wildlife",
    "Bosses",
    "Thralls",
    "NPCs",
    "Chests",
    "Iron Ore",
    "Resources",
    "Brimstone",
    "Crystal",
    "Map Markers",
    "Emotes",
    "Recipes",
  ],
  topFilters: [
    "cave",
    "dungeon",
    "ruins",
    "chest_metal",
    "wildlife_boss",
    "res_iron_ore",
    "res_crystal",
  ],
};
