name: Satisfactory Preview

on:
  push:
    paths:
      - "apps/satisfactory-overwolf/manifest.json"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Build Overwolf app
        run: bunx turbo run build --filter=satisfactory-overwolf...
      - name: Release Overwolf app
        env:
          OW_CLI_EMAIL: ${{ secrets.OW_CLI_EMAIL }}
          OW_CLI_API_KEY: ${{ secrets.OW_CLI_API_KEY }}
          PREVIEW_ACCESS_CHANNEL_ID: 980
        run: bunx turbo run release --filter=satisfactory-overwolf...
      - name: Promote tested build to production
        env:
          OW_CLI_EMAIL: ${{ secrets.OW_CLI_EMAIL }}
          OW_CLI_API_KEY: ${{ secrets.OW_CLI_API_KEY }}
          OW_APP_ID: mgpcocpamehmkagnkjcbabcnnhbebclkiekekhmg
          PREVIEW_ACCESS_CHANNEL_NAME: preview-access
        run: bunx turbo run promote --filter=satisfactory-overwolf
